[run]
allow-parallel-runners = true
print-linter-name = true
timeout = "5m0s"

[linters]
enable-all = true
disable = [
    # To be fixed
    "bodyclose",
    "cyclop",
    "dupl",
    "errcheck",
    "errname",
    "errorlint",
    "exhaustive",
    "exhaustivestruct",
    "exportloopref",
    "forbidigo",
    "forcetypeassert",
    "funlen",
    "gci",
    "gochecknoglobals",
    "gochecknoinits",
    "gocognit",
    "goconst",
    "gocritic",
    "gocyclo",
    "godot",
    "godox",
    "goerr113",
    "gofumpt",
    "gomnd",
    "gomoddirectives",
    "gosec",
    "ifshort",
    "lll",
    "makezero",
    "nakedret",
    "nestif",
    "nilerr",
    "nlreturn",
    "noctx",
    "paralleltest",
    "prealloc",
    "predeclared",
    "promlinter",
    "revive",
    "staticcheck",
    "stylecheck",
    "tagliatelle",
    "testpackage",
    "thelper",
    "unconvert",
    "unparam",
    "wastedassign",
    "whitespace",
    "wrapcheck",
    "wsl",
    # New in golangci-lint 1.45 but would be nice to address
    "varnamelen",
    "ireturn",
    "containedctx",
    "contextcheck",
    "maintidx",
    "nilnil",
    # Deprecated linters
    "golint",
    "interfacer",
    "maligned",
    "scopelint"
]

[misspell]
ignore-words = [
    "a.k.a",
    "ABI",
    "ABIs",
    "allowlist",
    "allowlisted",
    "api",
    "async",
    "barnabee",
    "base64",
    "blockchain",
    "Buf",
    "codegen",
    "cyclomatic",
    "datanode",
    "datestamps",
    "datetime",
    "denylist",
    "Docker",
    "DoD",
    "DoR",
    "Ed25519",
    "enum",
    "enums",
    "ERC20",
    "Ethereum",
    "expiryTime",
    "faucet",
    "fix-a-thon",
    "github",
    "GitLab",
    "GlobalRewardPool",
    "godog",
    "Golang",
    "golangci-lint",
    "GraphQL",
    "gRPC",
    "hotfix",
    "Ilya",
    "init",
    "lifecycle",
    "linters",
    "MacOSX",
    "MarkToMarket",
    "mempools",
    "multisig",
    "mutex",
    "mutexes",
    "nodewallet",
    "notarising",
    "pendingStake",
    "Prometheus",
    "proto",
    "protobuf",
    "protobufs",
    "PubKey",
    "Ropsten",
    "round_pushpin",
    "spec",
    "specs",
    "struct",
    "SubmitTransaction",
    "Suzdalnitski",
    "syslog",
    "tada",
    "tamlyn10",
    "tendermint",
    "Tendermint",
    "testnet",
    "tradable",
    "traderbot",
    "TradingService",
    "TxErr",
    "uint64",
    "unexported",
    "unparked",
    "vega",
    "whitepaper",
    "xor",
]

[staticcheck]
go = "1.16"
checks = ["all", "-ST1000", "-ST1016", "-SA1019"]

# protoc doesn't want us copying protobuf messages because they can have some internal state
# that shouldn't be copied; but we do it a lot. see below for details
# https://stackoverflow.com/questions/64183794/why-do-the-go-generated-protobuf-files-contain-mutex-locks
[[issues.exclude-rules]]
linters = ["govet"]
text = "impl.MessageState contains sync.Mutex"
